import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const pollId = router.query.pollId as string;
  const { data, isLoading } = api.poll.getPoll.useQuery(
    { pollId },
    {
      enabled: !!pollId,
    }
  );

  return (
    <>
      <Head>
        <title>Answer a Poll</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
